### ISSUE TITLE
What is `run_zoe_func` in the GLM HMM?

### ISSUE THREAD

**Issue by RylanSchaeffer** [int-brain-lab/analysis#6]
https://github.com/int-brain-lab/analysis/blob/a9f1297851d489667e50fdaf21a31d22050c87d7/python/glm_hmm_schema.py#L88

uses a function `run_zoe_func()`, but I don't see the function imported, and neither my IDE nor GitHub can find the source. Does anyone know where I can find said function?

**Comment by RylanSchaeffer** [comment]
@anne-urai , it looks like you made the commit. Would you happen to know?

**Comment by anne-urai** [comment]
Unfortunately this is preliminary code that refers to a yet-to-be released package @zashwood is writing. Stay tuned!

In general, everything in this `analysis` repo should be considered work in progress and will change fast. As we release more stable code, we'll usually put those in separate repositories and describe it in a preprint we release.

**Comment by RylanSchaeffer** [comment]
Ah, thanks for clarifying!
